[supervisord]
nodaemon=true

[program:importer]
command=/bin/bash /app/run_hourly.sh
autostart=true
autorestart=true
stdout_logfile=/app/importer/importer.log
stderr_logfile=/app/importer/importer_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5
